# Candidates aux élections africaines
SELECT DISTINCT ?person WHERE {
  ?country wdt:P30 wd:Q15 .
  ?person wdt:P27 ?country .
  ?person wdt:P106 wd:Q19772737 .
  FILTER NOT EXISTS { ?person wdt:P570 [] }
}
