# Gouverneurs africains
SELECT DISTINCT ?person WHERE {
  VALUES ?country { {{COUNTRIES}} }
  ?person wdt:P27 ?country .
  ?person wdt:P39 wd:Q13218630 .
  FILTER NOT EXISTS { ?person wdt:P570 [] }
}
